### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Minimata** [akkuman/gitea-release-action#6]
Hello there and thank you for providing this action.

I've met an issue that I can't solve and therefore come here for help.

I have recently re-enabled this action in a workflow, which means it used to work before.
Right now however, it fails right away and these are all the logs available:

```javascript
file:///run/act/actions/akkuman-gitea-release-action@v1/dist/index.js:18185
      const responseObject = new Response(response.body?.source ?? null)
                                                        ^
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:4[2](https://git.game-dev.space/minimata/MovementTests/actions/runs/41/jobs/1#jobstep-7-2):21)
```

Here's more or less my workflow:

```yaml
jobs:
  BumpTag:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.bump-tag.outputs.new_tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: bump-tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_API_TAGGING: false
          WITH_V: true
          PRERELEASE: false
          INITIAL_VERSION: 0.1.0
          DEFAULT_BUMP: patch

  Export:
    runs-on: ubuntu-latest
    needs: BumpTag
    container:
      image: barichello/godot-ci:mono-4.4.1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Import resources and build solution
        run: |
          godot --headless --editor --build-solutions --quit --import --path $PWD          
      - name: Build Windows
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --build-solutions --import --export-release "Windows Desktop" build/windows/${{ env.GAME_NAME }}.exe
          zip -r Windows.zip build/windows
      - name: Upload to release
        uses: akkuman/gitea-release-action@v1
        with:
          name: Running release
          tag_name: ${{ needs.BumpTag.outputs.tag_name }}
          files: |-
            Windows.zip
```

Note that I'm running these actions in a container using image `barichello/godot-ci:mono-4.4.1`, which may be relevant.
I have updated my Gitea version from 1.21 to 1.24 recently and I'm using the gitea/act_runner:nightly container. 

Do you have any idea what the issue could be ? Maybe something missing in the image I'm using ?

Cheers and thanks again.
